*&---------------------------------------------------------------------*
*& Include          ZISSUE_BLOCKED_DD
*&---------------------------------------------------------------------*

TYPES: BEGIN OF ty_eban,
         banfn TYPE banfn,
         bnfpo TYPE bnfpo,
         bsart TYPE bbsrt,
         ekgrp TYPE ekgrp,
         matnr TYPE matnr,
         werks TYPE ewerk,
         lgort TYPE lgort_d,
         matkl TYPE matkl,
         badat TYPE badat,
         lpein TYPE lpein,
       END OF ty_eban,

       BEGIN OF ty_final_alv,
         banfn    TYPE banfn,
         bnfpo    TYPE bnfpo,
         bsart    TYPE bbsrt,
         ekgrp    TYPE ekgrp,
         matnr    TYPE matnr,
         werks    TYPE ewerk,
         lgort    TYPE lgort_d,
         matkl    TYPE matkl,
         badat    TYPE badat,
         lpein    TYPE lpein,
         menge    TYPE bamng,
         sakto    TYPE saknr,
         kokrs    TYPE kokrs,
         check(1) TYPE c,
       END OF ty_final_alv,

       BEGIN OF ty_pr_delete,
         banfn    TYPE banfn,
         bnfpo    TYPE bnfpo,
         bsart    TYPE bbsrt,
         ekgrp    TYPE ekgrp,
         matnr    TYPE matnr,
         werks    TYPE ewerk,
         lgort    TYPE lgort_d,
         matkl    TYPE matkl,
         badat    TYPE badat,
         lpein    TYPE lpein,
         menge    TYPE bamng,
         sakto    TYPE saknr,
         kokrs    TYPE kokrs,
         check(1) TYPE c,
       END OF ty_pr_delete,

       BEGIN OF ty_mara,
         matnr TYPE matnr,
         mtart TYPE mtart,
         mbrsh TYPE mbrsh,
         matkl TYPE matkl,
         meins TYPE meins,
       END OF ty_mara,

       BEGIN OF ty_makt,
         matnr TYPE matnr,
         maktx TYPE maktx,
       END OF ty_makt,

       BEGIN OF ty_marc,
         matnr TYPE matnr,
         pstat TYPE pstat_d,
       END OF ty_marc,

       BEGIN OF ty_mat,
         matnr TYPE matnr,
         mtart TYPE mtart,
         mbrsh TYPE mbrsh,
         matkl TYPE matkl,
         meins TYPE meins,
         maktx TYPE maktx,
         pstat TYPE pstat_d,
       END OF ty_mat.


DATA: gt_eban            TYPE TABLE OF ty_eban,
      gt_final_eban      TYPE TABLE OF ty_final_alv,
      gt_pr_delete       TYPE TABLE OF ty_pr_delete,
      gt_mara            TYPE TABLE OF ty_mara,
      gt_makt            TYPE TABLE OF ty_makt,
      gt_marc            TYPE TABLE OF ty_marc,
      gt_final_mat       TYPE TABLE OF ty_mat,
      gt_final_eban_copy TYPE TABLE OF ty_final_alv,
      gwa_pr_delete      TYPE ty_pr_delete,
      gwa_final_mat      TYPE ty_mat,
      gwa_final_eban     TYPE ty_final_alv,
      gwa_eban           TYPE ty_eban.
